version: '3.8'

services:
  backend-app:
    build: 
      context: .
      dockerfile: Dockerfile.bun
    tty: true
    volumes:
      - ../:/home/user/app
    networks:
      - chat-app-network

networks:
  chat-app-network:
    external: true
